import Head from 'next/head'
import Image from 'next/image'
import hyve from '../public/hyve-example-image01.png'
import network from '../public/network-image.png'
import json from '../json/data.json'
import { useState, useEffect } from 'react'

export default function Home() {
  

 
console.log(json.data.content)
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col h-screen w-screen justify-center items-center overflow-hidden relative">
        
  
        <span className="flex flex-wrap justify-center w-rectangle h-4/5 white z-10  -rotate-6  absolute">
        <span className="flex  w-1/2 h-4 bg-green-light z-0   -ml-32 absolute right-20 top-4 "/>
        <span className="flex  w-1/2 h-4 bg-green-dark z-0   -ml-32 absolute right-20 top-8   "/>
        <span className="flex flex-wrap justify-center w-rectangle h-5/6 bg-rectangle z-10 mt-12  absolute"/>
        <span className="flex  w-1/2 h-4 bg-green-dark z-0   -ml-32 absolute left-48 bottom-16"/>  
        <span className="flex  w-3/5 h-4 bg-green-light z-0   -ml-32 absolute left-48 bottom-12"/>
        </span>
           <Image src={hyve} className="z-20 absolute xl:top-96 lg:top-16 lg:left-80  "/>

        <div className="z-20 lg:w-1/2 bg-white absolute lg:right-80 lg:bottom-20  shadow-md p-12">
          <h1 className="text-3xl z-30 font-semibold p-4 " >
      {json.data.title}
          </h1>
          <p className="p-4 w-2/3 leading-loose my-16">{json.data.content}
           <a href="" className="text-green-dark font-semibold">Read more.</a>
          </p> 
          <button className="p-5 px-8 m-3 bg-green-dark text-white font-semibold ">Why choose Hyve?</button>
          <Image src={network} className="-z-10 absolute top-0 right-0 "/>
        </div>

       
 
      </main>

   
    </div>
  )
}
